-- Public, non-personal Arabic activity library. Safe in production.
with seed(title, description, category, phases, devi, frame, energy, minutes, budget, place) as (values
('إعداد مشروب تحبه','قدّم مشروباً بسيطاً واسأل عن تفضيلها.','الراحة','{menstrual,luteal}','{E,I}','Calm Frame','low',10,'low','indoor'),
('تولي مهمة منزلية','اختر مهمة واضحة لتخفيف العبء دون استعراض.','المساعدة العملية','{menstrual,luteal}','{E,I}','Comfort Frame','medium',30,'free','indoor'),
('نزهة قصيرة','اقترح مشياً هادئاً مع مساحة لتغيير الخطة.','الخروج','{follicular,ovulation}','{V,D}','Fun Frame','medium',30,'free','outdoor'),
('تجربة مكان جديد','قدّم خيارين بسيطين لمكان غير معتاد.','التنوع','{follicular,ovulation}','{V,D}','Fun Frame','medium',60,'medium','outdoor'),
('حديث هادئ بلا هواتف','خصص وقتاً قصيراً للحضور والاستماع.','التواصل','{menstrual,luteal}','{E,I}','Comfort Frame','low',30,'free','indoor'),
('رسالة تقدير','اكتب تقديراً محدداً وصادقاً دون طلب مقابل.','التقدير','{menstrual,luteal,follicular,ovulation}','{E}','Comfort Frame','low',10,'free','either'),
('متابعة موضوع مهم','اسأل بلطف عن أمر سبق أن ذكرته.','الاستماع','{luteal,menstrual}','{I,E}','Comfort Frame','low',10,'free','either'),
('جلسة استماع','استمع دون مقاطعة أو تقديم حلول غير مطلوبة.','الاستماع','{menstrual,luteal}','{I,E}','Calm Frame','low',30,'free','indoor'),
('اختيار فيلم خفيف','اعرض خيارات قصيرة واترك لها الاختيار.','المرح','{follicular,luteal}','{V,I}','Fun Frame','low',120,'low','indoor'),
('ترتيب موعد بسيط','حدد وقتاً واضحاً وخطة مرنة.','التخطيط المشترك','{ovulation,follicular}','{D,V}','Dominant Frame','medium',60,'medium','either'),
('خطة نهاية الأسبوع','ضعا خيارين قابلين للتعديل معاً.','التخطيط المشترك','{follicular,ovulation}','{D,V}','Fun Frame','low',30,'free','indoor'),
('إعداد وجبة مفضلة','حضّر وجبة مألوفة أو اطلبها بعد السؤال.','الراحة','{menstrual,luteal}','{E,I}','Comfort Frame','medium',60,'medium','indoor'),
('منح مساحة هادئة','اعرض مساحة بلا انسحاب أو برود.','الراحة','{menstrual,luteal}','{I}','Calm Frame','low',30,'free','indoor'),
('سؤال مباشر عن تفضيلها','اسأل عما قد يناسبها اليوم بدل الافتراض.','التواصل','{menstrual,follicular,ovulation,luteal}','{I}','Calm Frame','low',10,'free','either'),
('موسيقى مشتركة','اختارا قائمة موسيقية هادئة أو مرحة.','المرح','{follicular,luteal}','{V,I}','Fun Frame','low',30,'free','indoor'),
('صورة وذكرى جميلة','شارك ذكرى لطيفة مع تقدير للحظة.','التقدير','{luteal,menstrual}','{E,I}','Comfort Frame','low',10,'free','either'),
('ترتيب ركن مريح','هيئ مكاناً بسيطاً للراحة.','الراحة','{menstrual,luteal}','{E,I}','Calm Frame','low',30,'low','indoor'),
('مشوار عملي معاً','اقترح إنجاز حاجة يومية دون ضغط.','المساعدة العملية','{follicular,luteal}','{D,E}','Comfort Frame','medium',60,'low','outdoor'),
('لعبة خفيفة','اختارا لعبة قصيرة لا تنافسية.','المرح','{follicular,ovulation}','{V}','Fun Frame','medium',30,'free','indoor'),
('مكالمة قصيرة للاطمئنان','تواصل باختصار واحترم انشغالها.','التواصل','{luteal,menstrual}','{E,I}','Comfort Frame','low',10,'free','either'),
('زيارة مقهى هادئ','اختارا مكاناً مريحاً وقريباً.','الخروج','{follicular,luteal}','{V,I}','Fun Frame','low',60,'medium','outdoor'),
('جولة في الحي','اخرجا بلا برنامج مزدحم.','الخروج','{follicular,ovulation}','{V}','Fun Frame','medium',30,'free','outdoor'),
('تحضير فطور بسيط','ابدأ اليوم بلفتة عملية لطيفة.','المساعدة العملية','{menstrual,luteal}','{E}','Comfort Frame','medium',30,'low','indoor'),
('ترتيب قائمة مهام','حددا الأولويات وخففا غير الضروري.','التخطيط المشترك','{luteal}','{D,E}','Comfort Frame','low',30,'free','indoor'),
('اختيار وصفة جديدة','جربا وصفة سهلة معاً.','التنوع','{follicular,ovulation}','{V,D}','Fun Frame','medium',60,'medium','indoor'),
('قراءة مشتركة','شاركا نصاً قصيراً وممتعاً.','الأنشطة المنزلية','{menstrual,luteal}','{I,V}','Calm Frame','low',30,'free','indoor'),
('العناية بنبتة','اقضيا دقائق في رعاية نبات منزلي.','الأنشطة المنزلية','{follicular,luteal}','{V,I}','Calm Frame','low',10,'low','indoor'),
('مشاهدة الغروب','اقترح لحظة هادئة في مكان قريب.','الخروج','{luteal,follicular}','{I,V}','Comfort Frame','low',30,'free','outdoor'),
('ترتيب صور قديمة','اختارا صوراً جميلة دون إطالة.','الأنشطة المنزلية','{luteal}','{E,I}','Comfort Frame','low',30,'free','indoor'),
('إحضار وجبة خفيفة','اسأل عن الخيار المناسب وأحضره.','المساعدة العملية','{menstrual,luteal}','{E}','Comfort Frame','low',10,'low','either'),
('رسالة صباحية لطيفة','شارك تمنياً بيوم هادئ دون ضغط.','التقدير','{menstrual,luteal,follicular,ovulation}','{E}','Calm Frame','low',10,'free','either'),
('دعوة لنشاط حيوي','اعرض نشاطاً مرناً يناسب الطاقة.','الخروج','{ovulation,follicular}','{D,V}','Dominant Frame','high',60,'medium','outdoor'),
('خياران واضحان','قدّم خيارين عمليين واترك قرارها حراً.','التخطيط المشترك','{ovulation}','{D}','Dominant Frame','low',10,'free','either'),
('ثناء محدد','اذكر شيئاً حقيقياً تقدّره فيها.','التقدير','{ovulation,luteal}','{D,E}','Comfort Frame','low',10,'free','either'),
('استراحة شاي','اتركا المهام لعشر دقائق هادئة.','الراحة','{menstrual,luteal}','{I,E}','Calm Frame','low',10,'low','indoor'),
('تنظيم مساحة صغيرة','تعاونا في ترتيب درج أو رف فقط.','الأنشطة المنزلية','{follicular}','{V,D}','Fun Frame','medium',30,'free','indoor'),
('سؤال ممتع','ابدأ حديثاً بسؤال خفيف وغير شخصي.','المرح','{follicular,ovulation}','{V}','Fun Frame','low',10,'free','either'),
('المشي لشراء حاجة','اجمعا بين مهمة بسيطة ونزهة قصيرة.','المساعدة العملية','{follicular,luteal}','{V,E}','Fun Frame','medium',30,'low','outdoor'),
('وقت بلا خطط','اتركا مساحة هادئة دون برنامج.','الراحة','{menstrual,luteal}','{I}','Calm Frame','low',60,'free','indoor'),
('مراجعة خطة مشتركة','تأكدا أن الخطة ما زالت مناسبة لكليكما.','التخطيط المشترك','{luteal,follicular}','{D,I}','Comfort Frame','low',30,'free','indoor')
)
insert into public.activities(title_ar,description_ar,category,phase,devi_elements,frame_name,energy_requirement,communication_requirement,approximate_minutes,budget_level,indoor_outdoor)
select title,description,category,phases::cycle_phase[],devi,frame,energy::energy_level,'medium'::energy_level,minutes,budget::budget_level,place from seed
on conflict (title_ar) do update set
  description_ar = excluded.description_ar,
  category = excluded.category,
  phase = excluded.phase,
  devi_elements = excluded.devi_elements,
  frame_name = excluded.frame_name,
  energy_requirement = excluded.energy_requirement,
  communication_requirement = excluded.communication_requirement,
  approximate_minutes = excluded.approximate_minutes,
  budget_level = excluded.budget_level,
  indoor_outdoor = excluded.indoor_outdoor,
  is_active = true;
